# Generated by Django 3.2.12 on 2022-06-16 19:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSalon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salon', models.Field(default=None)),
                ('service', models.Field(default=None)),
                ('price_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=3)),
            ],
        ),
    ]
